# fly.toml file generated for language-api-alura on 2023-04-03T21:31:41-03:00

app = "language-api-alura"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[build]
  image = "tuanemendes/languagesapi:latest"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
